accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name = 'login_url'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('signup/', views.SignUp.as_view(), name = 'signup'),
]

blogging/urls.py
from django.contrib import admin
from django.urls import path, include
from blogs import urls
from accounts import urls

urlpatterns = [
    path('blogs/', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),

]

blogs/urls.py
from django.urls import path
from blogs import views

app_name = "blogs"

urlpatterns = [
    path('', views.PostListView.as_view(), name = 'post_list'),
    path('about/', views.AboutView.as_view(), name = 'about'),
    path('newpost/', views.CreateNewPost.as_view(), name = 'post_form'),
    path('comment/<int:pk>/', views.CreateNewComment.as_view(), name = 'comment_form'),
    path('postdetail/<int:pk>/', views.PostDetail.as_view(), name = 'post_detail'),
    path('postdelete/<int:pk>/', views.PostDelete.as_view(), name = 'post_delete'),
    path('postpublish/<int:pk>', views.post_publish, name = 'post_publish')
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return self.username

blogs/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, null = True)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    likes = models.IntegerField(null = True)
    created_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank = True, null = True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(is_approved = True)

    def get_absolute_url(self):
        return reverse('blogs:post_detail', kwargs = {'pk':self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blogs.Post', related_name = 'comments', on_delete=models.CASCADE, null = True)
    author = models.CharField(max_length = 200)
    text = models.TextField()
    created_date = models.DateTimeField(default = timezone.now)
    is_approved = models.BooleanField(default = False)

    def get_absolute_url(self):
        return reverse('blogs:post_list')

    def approve(self):
        self.is_approved = True
        self.save()

    def __str__(self):
        return self.text

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class SignUpForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    

blogs/forms.py
from django.forms import ModelForm
from blogs.models import Post, Comment

# Create the form class.
class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'text']

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from accounts.models import User
from accounts.forms import SignUpForm

# Create your views here.

class SignUp(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy("accounts:login_url")
    template_name = "accounts/signup.html"

    #def get_success_url(self):
    #    return reverse('login/')

blogs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, CreateView, DetailView, ListView, DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from blogs.forms import PostForm, CommentForm
from blogs.models import Post, Comment
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy,reverse

# Create your views here.

class AboutView(TemplateView):
    template_name = 'blogs/about.html'


class CreateNewPost(LoginRequiredMixin, CreateView):
    form_class = PostForm
    model = Post


class CreateNewComment(LoginRequiredMixin, CreateView):
    form_class = CommentForm
    model = Comment
    success_url = reverse_lazy('blogs:post_list')
    url = None

    def form_valid(self, form, *args, **kwargs):
        cur_form = form.save(commit=False)
        cur_form.post = Post.objects.filter(id = self.kwargs['pk'])[0]
        cur_form.save()
        return HttpResponseRedirect(reverse_lazy('blogs:post_detail', kwargs = self.kwargs))


class PostDetail(DetailView):
    model = Post


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.all()


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("blogs:post_list")

    def post(self, request, *args, **kwargs):
        if "confirm" in request.POST:
            return super(PostDelete, self).post(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('blogs:post_detail', kwargs = kwargs))


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blogs:post_detail', pk=pk)

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

<div class="">
  <form class="" method="POST">
    <h1>Log In</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
</div>


{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}

<div class="">
  <form class="" method="POST">
    <h1>Sign Up</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
</div>


{% endblock %}

blogs/templates/blogs/about.html
{% extends 'base.html' %}

{% block content %}

    <p>"Welcome to our blogging site !!"</p>

{% endblock %}

blogs/templates/blogs/comment_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="">
      <form class="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
      </form>
    </div>

{% endblock %}

blogs/templates/blogs/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button type="submit" name="confirm" value="Confirm">Confirm</button>
    <button type="submit" value=object.pk >Cancel</button>
  </form>
{% endblock %}

blogs/templates/blogs/post_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="">
    <h1>{{ post.title }}</h1>
    {% if post.published_date %}
      <p>{{ post.published_date }}</p>
    {% endif %}
  </div>

  {%  if user.is_authenticated %}
  <div class="">
    <button type="button" ><a href="{% url 'blogs:comment_form' pk=post.pk %}">Comment</a></button>
    <button type="button" ><a href="{% url 'blogs:post_delete' pk=post.pk %}">Delete Post</a></button>
    {% if not post.published_date %}
      <button type="button"><a href="{% url 'blogs:post_publish' pk=post.pk %}">Publish</a></button>
    {% endif %}
  </div>
  {% endif %}


  <div class="">
      <p>{{ post.text|safe|linebreaksbr }}</p>
  </div>


  <div class="">
      {% for comment in post.comments.all %}
        <div class="">
          <div class="">
            <h3>{{ comment.author }}</h3>
            <h6>{{ comment.created_date }}</h6>
          </div>
          <p>{{ comment.text|safe|linebreaksbr }}</p>
        </div>
      {%empty%}
          <p>"No comments posted !! "</p>
      {% endfor %}
  </div>
{% endblock %}

blogs/templates/blogs/post_form.html
{% extends 'base.html' %}

{% block content %}
    <form class="" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save</button>
    </form>
{% endblock %}

blogs/templates/blogs/post_list.html
{% extends 'base.html' %}

{% block content %}

    {% for post in post_list %}
      <div class="">
        <h3><a href=" {% url 'blogs:post_detail' pk=post.pk %} ">{{ post.title }}</a></h3>
        <p class = "text_max_len" >{{ post.text }}</p>
      </div>
    {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> Mind Blogging </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    {# Custom CSS#}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

  </head>
  <body class = "loader">
    <nav class="navbar navbar-default navbar_padding">
      <div class="container">
        <ul class = "nav nav-tabs navbar_display">
          <li> <a class = "navbar-brand big_brand navbar_elements" href="{% url 'blogs:post_list'%}"> Mind Blogging </a> </li>
          <li> <a class = "navbar_elements" href="{% url 'blogs:about' %}"> About </a> </li>
          <li> <a class = "navbar_elements" href="https://www.github.com"> Github </a> </li>
          <li> <a class = "navbar_elements" href="https://www.linkedin.com"> LinkedIn </a> </li>
        </ul>

        <ul class = "nav nav-tabs navbar-right navbar_display">
          {% if user.is_authenticated %}
            <li> <a class = "navbar_elements navbar_elements_right" href="{% url 'blogs:post_form' %}"> Create New Post </a> </li>
            <li> <a class = "navbar_elements navbar_elements_right" href="{% url 'accounts:logout' %}"> Logout </a> </li>
          {% else %}
            <li> <a class="nav navbar-right navbar_elements navbar_elements_right" href="{% url 'accounts:login_url' %}"> Login </a> </li>
            <li> <a class="nav navbar-right navbar_elements navbar_elements_right" href="{% url 'accounts:signup' %}"> SignUp </a> </li>
          {% endif %}
        </ul>

      </div>

    </nav>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                  <div class="blog_posts">
                    {% block content %}
                    {% endblock %}
                  </div>
                </div>
            </div>
        </div>
        {#SCRIPTS#}
  </body>
</html>